name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - release
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## Actual task
      - name: Check and build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check buildPlugin
